export const compiledPackages = [
	{ dir: "packages/core", name: "@ifi/oh-pi-core" },
	{ dir: "packages/cli", name: "@ifi/oh-pi-cli" },
	{ dir: "packages/web-client", name: "@ifi/pi-web-client" },
	{ dir: "packages/web-server", name: "@ifi/pi-web-server" },
];

export const publishedPackages = [
	...compiledPackages,
	{ dir: "packages/adaptive-routing", name: "@ifi/pi-extension-adaptive-routing" },
	{ dir: "packages/agents", name: "@ifi/oh-pi-agents" },
	{ dir: "packages/analytics-db", name: "@ifi/pi-analytics-db" },
	{ dir: "packages/analytics-extension", name: "@ifi/pi-analytics-extension" },
	{ dir: "packages/ant-colony", name: "@ifi/oh-pi-ant-colony" },
	{ dir: "packages/background-tasks", name: "@ifi/pi-background-tasks" },
	{ dir: "packages/cursor", name: "@ifi/pi-provider-cursor" },
	{ dir: "packages/diagnostics", name: "@ifi/pi-diagnostics" },
	{ dir: "packages/extensions", name: "@ifi/oh-pi-extensions" },
	{ dir: "packages/oh-pi", name: "@ifi/oh-pi" },
	{ dir: "packages/ollama", name: "@ifi/pi-provider-ollama" },
	{ dir: "packages/pi-bash-live-view", name: "@ifi/pi-bash-live-view" },
	{ dir: "packages/pi-pretty", name: "@ifi/pi-pretty" },
	{ dir: "packages/pi-remote-tailscale", name: "@ifi/pi-remote-tailscale" },
	{ dir: "packages/plan", name: "@ifi/pi-plan" },
	{ dir: "packages/prompts", name: "@ifi/oh-pi-prompts" },
	{ dir: "packages/providers", name: "@ifi/pi-provider-catalog" },
	{ dir: "packages/shared-qna", name: "@ifi/pi-shared-qna" },
	{ dir: "packages/skills", name: "@ifi/oh-pi-skills" },
	{ dir: "packages/spec", name: "@ifi/pi-spec" },
	{ dir: "packages/subagents", name: "@ifi/pi-extension-subagents" },
	{ dir: "packages/themes", name: "@ifi/oh-pi-themes" },
	{ dir: "packages/web-remote", name: "@ifi/pi-web-remote" },
];
